### ISSUE TITLE
xorNumber 似乎会跟随微信的版本变化而变化

### ISSUE THREAD

**Issue by mywaiting** [z-jack/wxapkg_decryptor#3]
微信 Windows 2.8.0.121 （2020/03/26当天下载），其导出的 miniapp 无法 unpack

代码出错在 fileList = null  我没有仔细 debug

猜测 xorNumber 处不一定是 0x66

**Comment by z-jack** [comment]
好像和小程序的appid也有一些关联 我再研究一下之后更新上去 谢谢反馈

**Comment by mywaiting** [comment]
You can take some tips here [XXXXXXXXXXXX](https://blog.csdn.net/qq_43572067/article/details/100062493)

Please attach OD to WXAMDecoder.dll , when you open the mini app, in the moment you can see all source code dump in memory

I am lazy to decode the cryption in miniapp, but it is easy by hooking a function in wechat desktop exe

Thanks very much. Your code is inspiring me so much.

**Comment by mywaiting** [comment]
And more, due to some law exception, please remove the master brand display in github by default

You can take a brand just like `rm code` brand display in github

If someone really need this code, she/he will find it by the keyword `V1MMWX` which is unique in your repo

I write this by english duo to so much `ShenShouDang` 

and more, code comment with english is a good habit  :)
